services:
    db:
        image: postgres:16
        container_name: journal-postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: journaldb
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./db/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql

volumes:
    pgdata:
